- name: Configure instance , install apache and deploy hello world
  hosts: webserver
  sudo: yes
  remote_user: ubuntu
  gather_facts: False
  vars:
   ansible_ssh_private_key_file: keypair.pem
  tasks:
   - name: Upgrading Repo
     raw: sudo apt-get -y update
   - name: install  python
     raw: sudo apt-get -y install python
   - name: install apache
     raw:  sudo apt-get -y install apache2
     #apt: pkg=apache2 state=installed
   - name: Start Apache
     service: name=apache2 state=started
   - name: Create Hello World
     raw: echo "<h1>Hello World</h1>" > /var/www/html/index.html
